const {existing}=require('./env.cjs'),assert=require('node:assert/strict'),fs=require('node:fs');
const origin='http://127.0.0.1:4173',results=[];
(async()=>{const browser=await existing('playwright').chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
const ctx=await browser.newContext({viewport:{width:390,height:844}}),p=await ctx.newPage();await p.goto(origin);await p.keyboard.press('Tab');assert.equal(await p.locator(':focus').innerText(),'本文へスキップ');await p.keyboard.press('Enter');assert.equal(await p.locator(':focus').getAttribute('id'),'main');
await p.locator('.menu-toggle').focus();await p.keyboard.press('Enter');assert.ok(await p.locator('#mobile-menu').isVisible());await p.keyboard.press('Tab');assert.ok(await p.locator('#mobile-menu :focus').count());await p.keyboard.press('Escape');assert.ok(!await p.locator('#mobile-menu').isVisible());assert.equal(await p.locator(':focus').getAttribute('class'),'menu-toggle secondary');results.push('Keyboard skip link, mobile menu Enter/Tab/Escape/focus restore PASS');
await p.goto(origin+'/faq/index.html');for(const s of await p.locator('main summary').all()){await s.focus();await p.keyboard.press('Enter');assert.ok(await s.evaluate(e=>e.parentElement.open));}results.push('All 11 source FAQ + supplemental FAQ keyboard PASS');
await p.goto(origin+'/reservation/slots/index.html');await p.locator('.slot[data-state=open]').first().waitFor();await p.locator('.slot[data-state=open]').first().focus();await p.keyboard.press('Enter');assert.equal(await p.locator('.slot:focus').getAttribute('aria-pressed'),'true');const outline=await p.locator(':focus').evaluate(e=>getComputedStyle(e).outlineWidth);assert.notEqual(outline,'0px');await p.locator('[data-action=slot-next]').focus();await p.keyboard.press('Enter');await p.locator('#login').waitFor();await p.locator('[name=password]').focus();await p.keyboard.type('demo1234');await p.keyboard.press('Tab');await p.keyboard.press('Enter');await p.locator('#reservation-form').waitFor();await p.locator('[name=consent]').focus();await p.keyboard.press('Space');await p.keyboard.press('Tab');await p.keyboard.press('Enter');await p.locator('#reservation-confirm').waitFor();results.push('Keyboard slot/login/form/confirm and visible focus PASS');
await p.goto(origin+'/admin/login/index.html');await p.locator('[name=password]').focus();await p.keyboard.type('demo1234');await p.keyboard.press('Tab');await p.keyboard.press('Enter');await p.locator('.stats').waitFor();await p.goto(origin+'/admin/slots/index.html');await p.locator('[data-slot-id]').first().waitFor();const row=p.locator('[data-slot-id]').first();await row.locator('select').focus();await p.keyboard.press('End');await p.keyboard.press('Tab');await p.keyboard.press('Tab');assert.equal(await p.locator(':focus').innerText(),'保存');await p.keyboard.press('Enter');await p.locator('.toast').filter({hasText:'保存しました'}).waitFor();results.push('Keyboard admin slot select/save PASS');
const reduced=await browser.newContext({reducedMotion:'reduce'}),r=await reduced.newPage();await r.goto(origin);assert.equal(await r.locator('.hero-image img').evaluate(e=>getComputedStyle(e).animationName),'none');assert.equal(await r.locator('html').evaluate(e=>getComputedStyle(e).scrollBehavior),'auto');results.push('Reduced motion disables animation and smooth scrolling PASS');
const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}}),n=await nojs.newPage();for(const path of ['index.html','medical/index.html','about/index.html','access/index.html','faq/index.html','news/index.html','news/detail.html?id=source-1','first-visit/index.html']){await n.goto(origin+'/'+path);assert.ok((await n.locator('body').innerText()).includes('東京都台東区上野0-0-0'));assert.ok(await n.locator('.site-footer nav a').count());}await n.goto(origin+'/faq/index.html');await n.locator('main summary').first().click();assert.ok(await n.locator('main details').first().getAttribute('open')!==null);results.push('All public pages JS-off basic text/navigation, native FAQ PASS');
// 200% text only (font size) and subpath assets/navigation.
for(const path of ['index.html','medical/index.html','about/index.html','access/index.html','reservation/slots/index.html','reservation/form/index.html','admin/slots/index.html']){await p.goto(origin+'/'+path);await p.waitForTimeout(60);await p.addStyleTag({content:'html{font-size:32px}body{font-size:36px}'});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),path+' 200% text');}
results.push('390px + 200% root/body text reflow representative pages PASS');
await p.goto(origin+'/mock/hp/sato/index.html');await p.locator('.mobile-actions a').last().click();assert.ok(p.url().includes('/mock/hp/sato/reservation/'));await p.locator('#app a[href$="reservation/slots/index.html"]').click();await p.locator('.slot').first().waitFor();assert.ok(await p.locator('.slot').count()>0);assert.ok(p.url().includes('/mock/hp/sato/reservation/slots/'));results.push('Subpath static assets, dynamic module links and slot render PASS');
// Source paragraphs are copied verbatim into emitted HTML, excluding source-only instructions.
const source=JSON.parse(fs.readFileSync('src/content/source.json')),top=fs.readFileSync('src/index.html','utf8'),med=fs.readFileSync('src/medical/index.html','utf8'),about=fs.readFileSync('src/about/index.html','utf8'),faq=fs.readFileSync('src/faq/index.html','utf8');for(const m of source.medical)assert.ok(med.includes(m.body));for(const m of source.medical.slice(0,4))assert.ok(top.includes(m.body));for(const m of source.medical.slice(4))assert.ok(!top.includes(m.body));for(const f of source.faq){assert.ok(faq.includes(f.q));assert.ok(faq.includes(f.a));}for(const text of [...source.about.matchAll(/<(p|li|td)[^>]*>([\s\S]*?)<\/\1>/g)].map(x=>x[2]))assert.ok(about.includes(text),text.slice(0,50));assert.ok(top.includes(source.greeting));assert.deepEqual([...top.matchAll(/<section class="[^"]*" id="([^"]+)"/g)].map(m=>m[1]),['hero','hours','news','greeting','medical','about','staff','access']);results.push('Source exact medical/FAQ/about/staff/greeting and TOP order/count PASS');
}catch(e){results.push('FAIL '+e.stack)}finally{await browser.close();fs.writeFileSync('output/playwright/accessibility-results.json',JSON.stringify(results,null,2));console.log(results.join('\n'));if(results.some(s=>s.startsWith('FAIL')))process.exitCode=1}})();
