const fs=require('node:fs'),path=require('node:path');
const c=JSON.parse(fs.readFileSync('src/content/source.json','utf8'));
const routes={'index.html':'地域に根ざした医療','news/index.html':'お知らせ','news/detail.html':'お知らせ詳細','medical/index.html':'診療内容','about/index.html':'当院について','access/index.html':'診療時間・所在地','faq/index.html':'よくあるご質問','first-visit/index.html':'初めて受診される方へ','reservation/index.html':'Web予約','reservation/slots/index.html':'日時を選ぶ','reservation/form/index.html':'予約情報の入力','reservation/confirm/index.html':'予約内容の確認','reservation/complete/index.html':'予約完了','auth/register/index.html':'会員登録','auth/register/confirm.html':'登録内容の確認','auth/register/complete.html':'会員登録完了','auth/login/index.html':'ログイン','member/index.html':'マイページ','member/history/index.html':'過去の予約・利用履歴','member/reservation-detail/index.html':'予約の詳細','admin/login/index.html':'管理者ログイン','admin/index.html':'管理ダッシュボード','admin/reservations/index.html':'予約管理','admin/slots/index.html':'予約枠管理','admin/news/index.html':'お知らせ管理','admin/members/index.html':'会員管理'};
const nav=[['medical/index.html','診療内容'],['about/index.html','当院について'],['access/index.html','診療時間・所在地'],['faq/index.html','よくあるご質問']];
let prefix='';
const link=(url,text,cl='')=>`<a class="${cl}" href="${prefix+url}">${text}</a>`;
const button=(url,text,secondary=false)=>link(url,`${text}<span aria-hidden="true">↗</span>`,secondary?'button secondary':'button');
const photo=(name,alt,cl='')=>`<img class="${cl}" src="${prefix}assets/images/${name}.webp" alt="${alt}" width="1000" height="700" loading="lazy">`;
const heading=(en,title)=>`<div class="section-title"><span class="eyebrow">${en}</span><h2>${title}</h2></div>`;
const hours=()=>`<div class="hours-desktop">${c.hours}</div><div class="hours-mobile"><dl><dt>月・火・水・金</dt><dd>9:00〜12:00<br>13:00〜18:00</dd><dt>土</dt><dd>9:00〜12:00</dd></dl><p>受付時間：午前　8:00〜11:00　／　午後　12:00〜17:00</p><p>休診日：木曜・土曜午後・日曜</p><p class="small">※祝祭日も診療を行っておりますが、休診日もございますので、事前にご確認ください。</p></div>`;
const news=()=>c.news.map(n=>`<article class="news-row" data-news-id="${n.id}"><span class="tag">医院から</span>${link('news/detail.html?id='+n.id,n.title+'<span aria-hidden="true">↗</span>')}<span class="small">支給原稿</span></article>`).join('');
const staffNames=['佐藤 太郎','鈴木 真理','高橋 由美','山本 花'],staffRoles=['院長','看護師長','臨床検査技師','医療事務'];
const staff=()=>`<div class="staff-list">${staffNames.map((n,i)=>`<div><span class="eyebrow">0${i+1}</span><p>${staffRoles[i]}</p><h3>${n}</h3></div>`).join('')}</div>`;
const map=()=>`<figure class="map">${photo('map','支給された参考地図。架空住所のため実際の経路案内には利用できません。')}<figcaption>参考Map（支給素材）・教材用の架空所在地です。</figcaption></figure>`;
const access=()=>`<div class="split"><div>${heading('ACCESS','いつもの街で、<br>身近な医療を。')}<p>〒123-4567<br>東京都台東区上野0-0-0</p><p>JR上野駅より徒歩5分<br>当院専用 無料駐車場 10台分</p>${button('access/index.html','診療時間・所在地',true)}</div>${map()}</div>`;
function top(){return `<section class="hero" id="hero"><div class="hero-image"><img src="${prefix}assets/images/firstView.webp" srcset="${prefix}assets/images/firstView-800.webp 800w, ${prefix}assets/images/firstView.webp 1600w" sizes="(max-width: 700px) 100vw, 94vw" width="1920" height="1098" alt="医師と患者が笑顔で話す診療対話イメージ" fetchpriority="high"></div><div class="hero-copy"><span class="eyebrow">SATO CLINIC · UENO</span><h1>地域に根ざした医療</h1><p>あなたと、ご家族の毎日に。<br>安心して相談できる、かかりつけ医。</p><div class="actions">${button('reservation/index.html','Web予約')}${button('access/index.html','診療時間を見る',true)}</div><p class="small">一般診療は予約優先制です。</p></div><div class="hero-bottom"><span>内科・循環器科・呼吸器科</span><span>SCROLL ↓</span></div></section>
<section class="section container hours-section" id="hours"><div>${heading('CONSULTATION HOURS','診療時間')}<p class="small">ご来院の前にご確認ください。</p>${link('first-visit/index.html','初めて受診される方へ ↗','text-link')}</div><div>${hours()}</div></section>
<section class="section soft" id="news"><div class="container split news-split"><div>${heading('NEWS','お知らせ')}${link('news/index.html','すべてのお知らせ ↗','text-link')}</div><div data-news-list="5">${news()}</div></div></section>
<section class="section container" id="greeting"><div class="split greeting"><figure>${photo('sato_taro','院長 佐藤 太郎')}<figcaption>佐藤医院　院長　佐藤 太郎</figcaption></figure><div>${heading('MESSAGE','一人ひとりに寄り添い、<br>地域とともに。')}<div class="prose">${c.greeting}</div></div></div></section>
<section class="section soft" id="medical"><div class="container">${heading('OUR CARE','診療内容')}<p class="lead">${c.medicalLead}</p><div class="care-grid">${c.medical.slice(0,4).map((m,i)=>`<article><span class="chapter">0${i+1}</span><h3>${m.title}</h3><p>${m.body}</p></article>`).join('')}</div>${button('medical/index.html','すべての診療内容を見る',true)}</div></section>
<section class="section container" id="about"><div class="split"><div>${heading('ABOUT US','患者様の声に耳を傾け、<br>共に歩む医療。')}<p>${c.aboutIntro}</p>${button('about/index.html','当院について',true)}</div><figure>${photo('patient_1','診療イメージ')}<figcaption>診療イメージ</figcaption></figure></div></section>
<section class="section container" id="staff">${heading('OUR TEAM','スタッフ紹介')}${staff()}${link('about/index.html#team','プロフィールを見る ↗','text-link')}</section>
<section class="section soft" id="access"><div class="container">${access()}</div></section>`;}
function publicContent(route){
if(route==='medical/index.html')return `<p class="lead">${c.medicalLead}</p><nav class="chapter-nav" aria-label="診療内容の目次">${c.medical.map((m,i)=>`<a href="#care-${i+1}">0${i+1} ${m.title}</a>`).join('')}</nav>${c.medical.map((m,i)=>`<section class="editorial" id="care-${i+1}"><span class="chapter">0${i+1}</span><div><h2>${m.title}</h2><p>${m.body}</p></div>${i===0||i===4?`<figure>${photo(i===0?'medical_1':'medical_3','診療イメージ')}<figcaption>診療イメージ</figcaption></figure>`:''}</section>`).join('')}${button('reservation/index.html','Web予約へ進む')}`;
if(route==='about/index.html'){let a=c.about.replace('<h3>スタッフ紹介</h3>','<h2 id="team">スタッフ紹介</h2>');a=a.replace(/<h3>(.*?)<\/h3>/g,'<h2>$1</h2>');return `<div class="about-layout"><aside>${photo('sato_taro','院長 佐藤 太郎')}<p>院長　佐藤 太郎</p></aside><div class="prose">${a}</div></div><section class="section">${heading('CARE GALLERY','診療イメージ')}<p class="small">支給素材によるイメージです。医院の実設備を示すものではありません。</p><div class="gallery" tabindex="0" aria-label="診療イメージ。横にスクロールできます">${['medical_1','medical_3','patient_1'].map(n=>photo(n,'診療イメージ')).join('')}</div></section>`;}
if(route==='access/index.html')return `<div class="split"><div class="prose access-copy">${c.access.replace('診療時間（基本情報マスタと同一）','診療時間').replace(/<table>[\s\S]*?<\/table>/,m=>`<div class="hours-desktop">${m}</div><div class="hours-mobile"><p>月・火・水・金：9:00〜12:00 / 13:00〜18:00<br>土：9:00〜12:00</p></div>`)}</div>${map()}</div>`;
if(route==='faq/index.html')return `<p class="lead">当院に関するご質問をまとめました。その他のご不明点がございましたら、スタッフまでお気軽にお問い合わせください。</p><div class="reading">${c.faq.map(f=>`<details><summary>${f.q}</summary><p>${f.a}</p></details>`).join('')}<h2>Web予約について</h2><details><summary>このサイトで実際の予約はできますか？</summary><p>こちらは教材用のデモです。予約・会員登録はこのブラウザ内での体験となり、実際の受診予約やメール送信は行われません。</p></details></div>`;
if(route==='first-visit/index.html')return `<div class="reading"><p class="lead">受診前の確認から、ご予約まで。</p><section class="editorial"><span class="chapter">01</span><div><h2>ご予約について</h2><p>${c.faq[0].a}</p>${button('reservation/index.html','空き状況を見る')}</div></section><section class="editorial"><span class="chapter">02</span><div><h2>お持ちいただくもの</h2><p>${c.faq[1].a}</p></div></section><section class="editorial"><span class="chapter">03</span><div><h2>発熱・風邪症状のある方へ</h2><p>${c.news[3].body}</p></div></section>${button('faq/index.html','よくあるご質問',true)}</div>`;
if(route==='news/index.html')return `<p class="small">初期の記事は支給された確定原稿です。本文の日付・曜日は原稿の表記を保持しています。</p><div data-news-list="all">${news()}</div><div id="pagination"></div>`;
if(route==='news/detail.html')return `<div id="news-detail" class="reading">${c.news.map(n=>`<article id="${n.id}"><h2>${n.title}</h2><p>${n.body}</p></article>`).join('')}</div>${link('news/index.html','← お知らせ一覧へ','text-link')}`;
return '';}
function build(route){prefix='../'.repeat(route.split('/').length-1);const title=routes[route],isTop=route==='index.html',pub=isTop||/^(news|medical|about|access|faq|first-visit)\//.test(route),admin=route.startsWith('admin/');const links=nav.map(([u,t])=>link(u,t)).join('');
const body=isTop?top():`<div class="container"><nav class="breadcrumb" aria-label="パンくず">${link('index.html','ホーム')}<span aria-hidden="true">/</span><span>${title}</span></nav><header class="page-heading"><span class="eyebrow">${admin?'CLINIC MANAGEMENT':pub?'SATO CLINIC':'SATO CLINIC · WEB SERVICE'}</span><h1>${title}</h1></header>${pub?publicContent(route):`<div class="demo-note">体験用デモです。実際の予約・認証・メール送信は行いません。架空の情報でお試しください。</div><div id="app"><p role="status">画面を準備しています…</p><noscript>この機能の操作にはJavaScriptを有効にしてください。</noscript></div>`}</div>`;
const html=`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="佐藤医院のFrontend Design Mock。地域に根ざした医療。教材用の架空設定です。"><title>${title} | 佐藤医院</title><link rel="icon" href="${prefix}assets/images/logo.png"><link rel="stylesheet" href="${prefix}assets/css/style.css"><script type="module" src="${prefix}assets/js/main.js"></script></head><body data-route="${route}" class="${pub?'public':'application'} ${admin?'admin':''}"><a class="skip" href="#main">本文へスキップ</a><header class="site-header"><a class="brand" href="${prefix}index.html" aria-label="佐藤医院 ホーム"><img src="${prefix}assets/images/logo.png" width="210" height="61" alt="佐藤医院 Sato Clinic"></a><nav class="desktop-nav" aria-label="メイン">${links}</nav><div class="header-actions">${link('auth/login/index.html','ログイン','login-link')}${button('reservation/index.html','Web予約')}<button class="menu-toggle secondary" type="button" aria-haspopup="dialog" aria-controls="mobile-menu">メニュー<span aria-hidden="true">☰</span></button></div></header><dialog id="mobile-menu" aria-label="メニュー"><div class="dialog-head"><strong>メニュー</strong><button type="button" data-close>閉じる ×</button></div><nav aria-label="モバイル">${links}${link('news/index.html','お知らせ')}${link('first-visit/index.html','初めて受診される方へ')}${link('auth/login/index.html','ログイン')}${link('reservation/index.html','Web予約')}</nav></dialog><main id="main" tabindex="-1">${body}</main><footer class="site-footer"><div class="container"><div class="footer-grid"><div><img src="${prefix}assets/images/logo.png" width="230" height="67" alt="佐藤医院"><p>〒123-4567 東京都台東区上野0-0-0</p><p class="phone">00-0000-0000</p><p class="small">FAX：00-0000-0000<br>info@sato-clinic-test.jp</p></div><div><h2>診療のご案内</h2><p>午前 9:00〜12:00 / 午後 13:00〜18:00</p><p class="small">受付：午前 8:00〜11:00 / 午後 12:00〜17:00<br>休診：木曜・土曜午後・日曜<br>※祝祭日も診療を行っておりますが、休診日もございますので、事前にご確認ください。</p></div><nav aria-label="フッター">${links}${link('news/index.html','お知らせ')}${link('first-visit/index.html','初めて受診される方へ')}${link('member/index.html','マイページ')}${link('admin/login/index.html','管理者デモ')}</nav></div><details class="legal"><summary>デモの利用・プライバシーについて</summary><p>教材用の架空の医院です。実在する医院の情報ではありません。入力はこのブラウザ内に保存されます。実際の個人情報・パスワードは入力しないでください。実メール送信・本物の認証・医療予約は行いません。</p></details><div class="footer-bottom"><span>© Sato Clinic · Design Mock</span><span>地域に根ざした医療</span></div></div></footer>${pub?`<nav class="mobile-actions" aria-label="受診のご案内"><a href="tel:0000000000">電話</a>${link('access/index.html','診療時間')}${link('reservation/index.html','Web予約')}</nav>`:''}<div class="toast" role="status" aria-live="polite" hidden></div></body></html>`;
const out='src/'+route;fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,html);}
for(const route of Object.keys(routes)){if(process.argv.includes('--top')&&route!=='index.html')continue;build(route);}
fs.writeFileSync('src/content/routes.json',JSON.stringify(routes,null,2));
