const {existing}=require('./env.cjs'),assert=require('node:assert/strict'),fs=require('node:fs');
const origin='http://127.0.0.1:4173',results=[],errors=[];
const wait=async(p,s)=>p.locator(s).first().waitFor();
const fill=async(p,n,v)=>p.locator(`[name="${n}"]`).fill(v);
const click=async(p,s)=>p.locator(s).click();
const ensure=async(p,s,text)=>p.locator(s).filter({hasText:text}).first().waitFor();
(async()=>{const browser=await existing('playwright').chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const ctx=await browser.newContext({viewport:{width:1440,height:1000}});ctx.on('page',p=>{p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())})});const p=await ctx.newPage(),admin=await ctx.newPage();
try{
 await p.goto(origin);await click(p,'.desktop-nav a[href="medical/index.html"]');await ensure(p,'main','禁煙外来');await p.goto(origin+'/access/index.html');await ensure(p,'main','8:00〜11:00');await click(p,'.header-actions a[href="../reservation/index.html"]');await click(p,'#app a[href$="reservation/slots/index.html"]');await wait(p,'.slot');
 let slot=p.locator('.slot[data-state="open"]').first();if(!await slot.count()){await p.locator('[data-date]').nth(1).click();slot=p.locator('.slot[data-state="open"]').first()}const slotId=await slot.getAttribute('data-slot');await slot.click();await click(p,'[data-action="slot-next"]');await wait(p,'#login');await fill(p,'password','demo1234');await click(p,'#login button[type=submit]');await wait(p,'#reservation-form');
 await fill(p,'patient','');await click(p,'#reservation-form button[type=submit]');await ensure(p,'#form-errors','患者名');await fill(p,'patient','検証 花子');await p.locator('[name=consent]').check();await click(p,'#reservation-form button[type=submit]');await wait(p,'#reservation-confirm');await ensure(p,'#app','検証 花子');await click(p,'#reservation-confirm button[type=submit]');await wait(p,'.success-panel');await ensure(p,'#app','ご予約を受け付けました');const rid=await p.evaluate(()=>JSON.parse(sessionStorage.getItem('sato.completed-reservation')));await click(p,'#app a');await ensure(p,'#app','検証 花子');results.push('E2E-01 PASS: Public → slots → login → validation → form → confirm → complete → member');
 await admin.goto(origin+'/admin/login/index.html');await fill(admin,'password','demo1234');await click(admin,'#admin-login button[type=submit]');await wait(admin,'.stats');await admin.goto(origin+'/admin/reservations/index.html');await wait(admin,'[data-res-id]');await admin.locator(`[data-res-id="${rid}"] select`).selectOption('pending');await admin.locator(`[data-res-id="${rid}"] button`).click();await p.waitForFunction(()=>document.querySelector('#app').innerText.includes('要確認'));await p.goto(origin+'/member/reservation-detail/index.html?id='+rid);await ensure(p,'#app','要確認');results.push('E2E-04 PASS: Admin status → Member/dashboard/detail');
 await p.goto(origin+'/reservation/slots/index.html');await wait(p,'.slot');await admin.goto(origin+'/admin/slots/index.html');await wait(admin,'[data-slot-id]');const target=p.locator('.slot[data-state="open"]').first(),targetId=await target.getAttribute('data-slot');await admin.locator('[name=admin-date]').selectOption(targetId.slice(0,10));let row=admin.locator(`[data-slot-id="${targetId}"]`);await row.locator('select').selectOption('false');await row.locator('button').click();await p.waitForFunction(id=>document.querySelector(`[data-slot="${id}"]`).dataset.state==='closed',targetId);assert.ok(await p.locator(`[data-slot="${targetId}"]`).isDisabled());await row.locator('select').selectOption('true');await row.locator('[name=capacity]').fill('1');await row.locator('button').click();await p.waitForFunction(id=>document.querySelector(`[data-slot="${id}"]`).dataset.state==='low',targetId);results.push('E2E-02 PASS: Admin close/open/capacity → patient other tab');
 // Save-time conflict; the patient form must keep entered values.
 await p.locator(`[data-slot="${targetId}"]`).click();await click(p,'[data-action="slot-next"]');await wait(p,'#reservation-form');await fill(p,'patient','競合 デモ');await p.locator('[name=consent]').check();await click(p,'#reservation-form button[type=submit]');await wait(p,'#reservation-confirm');await row.locator('select').selectOption('false');await row.locator('button').click();await click(p,'#reservation-confirm button[type=submit]');await ensure(p,'#form-errors','満枠または受付停止');await click(p,'a[href$="reservation/form/index.html"]');assert.equal(await p.locator('[name=patient]').inputValue(),'競合 デモ');results.push('AC26 PASS: save-time conflict fails, values recover');
 // News: draft unpublished, publish synchronized and top remains at five.
 await p.goto(origin);await admin.goto(origin+'/admin/news/index.html');await wait(admin,'[data-action=news-new]');await click(admin,'[data-action=news-new]');await fill(admin,'title','検証用のお知らせ');await fill(admin,'body','新しいお知らせの本文です。<script>捏造なし</script>');await click(admin,'#news-edit button[type=submit]');await wait(admin,'[data-action=news-new]');assert.ok(!(await p.locator('[data-news-list]').innerText()).includes('検証用'));await admin.locator('.data-row').filter({hasText:'検証用のお知らせ'}).locator('button').click();await admin.locator('#news-edit [name=status]').selectOption('published');await click(admin,'#news-edit button[type=submit]');await p.waitForFunction(()=>document.querySelector('[data-news-list]').innerText.includes('検証用のお知らせ'));assert.equal(await p.locator('.news-row').count(),5);await p.goto(origin+'/news/index.html');await p.waitForFunction(()=>document.querySelectorAll('.news-row').length===6);await p.locator('.news-row').filter({hasText:'検証用のお知らせ'}).locator('a').click();await ensure(p,'#news-detail','<script>捏造なし</script>');assert.equal(await p.locator('#news-detail script').count(),0);results.push('E2E-03 PASS: draft → published → top/list/detail, source seed protected, escaped content');
 // Member change and cancellation.
 await p.goto(origin+'/member/reservation-detail/index.html?id='+rid);await click(p,'[data-action=change]');await wait(p,'#action-dialog[open]');await click(p,'#change-reservation button[type=submit]');await p.waitForSelector('#action-dialog',{state:'detached'});await click(p,'[data-action=cancel]');await click(p,'#cancel-reservation button[type=submit]');await p.waitForFunction(()=>document.querySelector('#app').innerText.includes('取消済み'));await p.reload();await ensure(p,'#app','取消済み');await p.goto(origin+'/member/history/index.html');await ensure(p,'#app','来院済み');results.push('AC29/30/37 PASS: change/cancel/history and reload persistence');
 // Mobile registration branch.
 const mobile=await ctx.newPage();await mobile.setViewportSize({width:390,height:844});await mobile.goto(origin);await mobile.locator('.mobile-actions a').last().click();await click(mobile,'#app a[href$="reservation/slots/index.html"]');await wait(mobile,'.slot');let ms=mobile.locator('.slot[data-state=open]').first();if(!await ms.count()){await mobile.locator('[data-date]').nth(1).click();ms=mobile.locator('.slot[data-state=open]').first()}await ms.click();await click(mobile,'[data-action=slot-next]');await click(mobile,'#app a[href$="auth/register/index.html"]');await fill(mobile,'name','モバイル 検証');await fill(mobile,'email','mobile@example.com');await fill(mobile,'phone','0000000000');await fill(mobile,'password','NeverStoreThis123');await mobile.locator('[name=consent]').check();await click(mobile,'#register button[type=submit]');await wait(mobile,'#register-confirm');assert.ok(!(await mobile.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).includes('NeverStoreThis123'));await click(mobile,'#register-confirm button[type=submit]');await ensure(mobile,'#app','会員登録が完了しました');await click(mobile,'#app a');await wait(mobile,'#reservation-form');await mobile.locator('[name=consent]').check();await click(mobile,'#reservation-form button[type=submit]');await wait(mobile,'#reservation-confirm');await click(mobile,'#reservation-confirm button[type=submit]');await wait(mobile,'.success-panel');await click(mobile,'#app a');await ensure(mobile,'#app','モバイル 検証');results.push('E2E-05 / AC27/28 PASS: Mobile TOP → slot → register → confirm → complete → booking → member; no password stored');
 // Members and login/logout.
 await admin.goto(origin+'/admin/members/index.html');await fill(admin,'search','モバイル');await click(admin,'[data-action=member-search]');assert.equal(await admin.locator('[data-member-id]').count(),1);await admin.locator('[data-member-id] select').selectOption('suspended');await admin.locator('[data-member-id] button').click();await mobile.waitForFunction(()=>document.querySelector('#app').innerText.includes('ログインして続ける'));await admin.reload();await ensure(admin,'#app','利用停止');await p.goto(origin+'/member/index.html');await click(p,'[data-action=logout]');await wait(p,'#login');assert.equal(await p.evaluate(()=>sessionStorage.getItem('sato.member')),null);results.push('AC28/36/37 PASS: member search/suspend, persistence, logout');
 // Storage event only fallback in a separate page.
 const fallback=await ctx.newPage();await fallback.addInitScript(()=>{window.BroadcastChannel=undefined});await fallback.goto(origin+'/reservation/slots/index.html');await wait(fallback,'.slot');if(!await fallback.locator('.slot[data-state=open]').count())await fallback.locator('[data-date]').nth(1).click();const fb=await fallback.locator('.slot[data-state=open]').first().getAttribute('data-slot');await admin.goto(origin+'/admin/slots/index.html');await wait(admin,'[data-slot-id]');await admin.locator('[name=admin-date]').selectOption(fb.slice(0,10));await admin.locator(`[data-slot-id="${fb}"] [name=open]`).selectOption('false');await admin.locator(`[data-slot-id="${fb}"] button`).click();await fallback.waitForFunction(id=>document.querySelector(`[data-slot="${id}"]`).dataset.state==='closed',fb);assert.equal(await fallback.getAttribute('body','data-last-sync'),'storage');results.push('AC34 PASS: BroadcastChannel disabled → storage fallback updates patient');
 fs.writeFileSync('output/playwright/demo-storage.json',JSON.stringify(await admin.evaluate(()=>JSON.parse(localStorage.getItem('sato-clinic.v1.1')))),null,2);
}catch(e){results.push('FAIL: '+e.stack);await p.screenshot({path:'output/playwright/e2e-failure.png',fullPage:true});}
fs.writeFileSync('output/playwright/e2e-results.json',JSON.stringify({results,errors},null,2));console.log(JSON.stringify({results,errors},null,2));await browser.close();if(results.some(x=>x.startsWith('FAIL'))||errors.length)process.exitCode=1;
})();
