const {existing}=require('./env.cjs'),assert=require('node:assert/strict'),fs=require('node:fs');
const origin='http://127.0.0.1:4173',results=[];
(async()=>{const browser=await existing('playwright').chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const ctx=await browser.newContext(),p=await ctx.newPage(),admin=await ctx.newPage();
// Patient listens to BroadcastChannel only: suppress registration of storage listeners.
await p.addInitScript(()=>{const native=window.addEventListener.bind(window);window.addEventListener=(type,...args)=>{if(type!=='storage')native(type,...args)}});await p.goto(origin+'/reservation/slots/index.html');await p.locator('.slot[data-state=open]').first().waitFor();const id=await p.locator('.slot[data-state=open]').first().getAttribute('data-slot');await admin.goto(origin+'/admin/login/index.html');await admin.locator('[name=password]').fill('demo1234');await admin.locator('#admin-login button').click();await admin.locator('.stats').waitFor();await admin.goto(origin+'/admin/slots/index.html');await admin.locator('[name=admin-date]').selectOption(id.slice(0,10));const row=admin.locator(`[data-slot-id="${id}"]`);await row.locator('[name=open]').selectOption('false');await row.locator('button').click();await p.waitForFunction(id=>document.querySelector(`[data-slot="${id}"]`).dataset.state==='closed',id);assert.equal(await p.getAttribute('body','data-last-sync'),'BroadcastChannel');results.push('BroadcastChannel-only patient update (storage listener suppressed) PASS');
// Capacity cannot be lowered below booked count; source cannot be modified.
const full=await admin.locator('[data-slot-id]').filter({hasText:'予約済み 2'}).first();await full.locator('[name=capacity]').fill('1');await full.locator('button').click();await admin.locator('#form-errors').filter({hasText:'予約済み人数以上'}).waitFor();results.push('Capacity below booked count rejected PASS');
await admin.goto(origin+'/admin/news/index.html');await admin.locator('[data-action=news-edit]').first().click();assert.equal(await admin.locator('#news-edit [name=id]').inputValue(),'');await admin.locator('#news-edit [name=title]').fill('複製確認');await admin.locator('#news-edit button[type=submit]').click();await admin.locator('.data-row').filter({hasText:'複製確認'}).waitFor();assert.equal((await admin.evaluate(()=>JSON.parse(localStorage.getItem('sato-clinic.v1.1')).news.filter(n=>n.source))).length,5);results.push('Protected news seed duplicated without altering originals PASS');
// Corrupt storage has an explicit error rather than an empty/success display.
const bad=await browser.newContext(),b=await bad.newPage();await b.goto(origin);await b.evaluate(()=>localStorage.setItem('sato-clinic.v1.1','{broken'));await b.goto(origin+'/reservation/slots/index.html');await b.locator('#app .error-box').filter({hasText:'データを読み込めませんでした'}).waitFor();results.push('Corrupt localStorage error UI PASS');
// Verify source DOCX paragraphs against corresponding supplied HTML files.
const zip=existing('jszip');for(const name of ['制作依頼書','掲載原稿']){const z=await zip.loadAsync(fs.readFileSync(`source/extracted/sato-clinic-reqkit/requirements/${name}.docx`));const xml=await z.file('word/document.xml').async('text');const texts=[...xml.matchAll(/<w:t(?:\s[^>]*)?>([\s\S]*?)<\/w:t>/g)].map(m=>m[1].replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>'));const html=fs.readFileSync(`source/extracted/sato-clinic-reqkit/requirements/${name}.html`,'utf8').replace(/<[^>]+>/g,'').replace(/&amp;/g,'&');const norm=s=>s.replace(/\s/g,'');const missing=texts.filter(t=>t.trim()&&!norm(html).includes(norm(t)));assert.equal(missing.length,0,name+': '+missing.join('|'));}results.push('Both source DOCX text runs match corresponding source HTML PASS');
}catch(e){results.push('FAIL '+e.stack)}finally{await browser.close();fs.writeFileSync('output/playwright/edge-results.json',JSON.stringify(results,null,2));console.log(results.join('\n'));if(results.some(x=>x.startsWith('FAIL')))process.exitCode=1}})();
