const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),cp=require('node:child_process'),{existing}=require('./env.cjs');
const origin='http://127.0.0.1:4173',results=[];
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)])}
(async()=>{for(const f of walk('src').filter(f=>f.endsWith('.js')))cp.execFileSync(process.execPath,['--check',f]);results.push('All delivered JavaScript syntax PASS');const browser=await existing('playwright').chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),ctx=await browser.newContext();try{const p=await ctx.newPage();await p.goto(origin+'/reservation/slots/index.html');await p.locator('.slot[data-state=open]').first().waitFor();await p.locator('.slot[data-state=open]').first().click();await p.evaluate(()=>{sessionStorage.setItem('sato.member','"demo-member"');sessionStorage.setItem('sato.admin','true');sessionStorage.setItem('sato.reservation-draft',JSON.stringify({patient:'検証 花子',phone:'0000000000',visit:'初診',consent:true}));sessionStorage.setItem('sato.completed-reservation','"seed-2"');sessionStorage.setItem('sato.register-draft',JSON.stringify({name:'検証 太郎',email:'test@example.com',phone:'0000000000'}))});
for(const r of Object.keys(JSON.parse(fs.readFileSync('src/content/routes.json')))){await p.goto(origin+'/'+r+(r==='news/detail.html'?'?id=source-1':r==='member/reservation-detail/index.html'?'?id=seed-2':''));await p.waitForTimeout(70);assert.equal(await p.locator('main').count(),1);assert.equal(await p.locator('h1').count(),1);assert.equal(await p.locator('html').getAttribute('lang'),'ja');const duplicates=await p.locator('[id]').evaluateAll(es=>es.map(e=>e.id).filter((id,i,all)=>all.indexOf(id)!==i));assert.deepEqual(duplicates,[],r);for(const width of [320,375,390,430,768,1024,1280,1440]){await p.setViewportSize({width,height:960});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),r+' '+width)}const invalid=await p.locator('input:not([type=hidden]),select,textarea').evaluateAll(es=>es.filter(e=>!e.labels?.length&&!e.getAttribute('aria-label')).map(e=>e.outerHTML));assert.deepEqual(invalid,[],r);for(const input of await p.locator('input:not([type=hidden]),select,textarea').all())assert.ok(Number.parseFloat(await input.evaluate(e=>getComputedStyle(e).fontSize))>=16,r);}
results.push('26 populated pages × 8 widths, lang/main/H1/unique IDs/labels/input font >=16px PASS');
for(const r of ['index.html','medical/index.html','about/index.html','access/index.html']){await p.goto(origin+'/'+r);await p.evaluate(async()=>{for(const i of document.images)i.loading='eager';await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})))});assert.deepEqual(await p.locator('img').evaluateAll(es=>es.filter(i=>!i.naturalWidth).map(i=>i.src)),[]);const bad=await p.locator('a[href]').evaluateAll(es=>es.filter(a=>new URL(a.href).origin===location.origin&&new URL(a.href).pathname===location.pathname&&new URL(a.href).hash&&!document.getElementById(decodeURIComponent(new URL(a.href).hash.slice(1)))).map(a=>a.href));assert.deepEqual(bad,[])}results.push('Public images decoded and same-page anchors resolve PASS');
assert.equal(await p.locator('body').evaluate(e=>getComputedStyle(e).fontSize),'18px');results.push('Body typography 18px PASS');
}catch(e){results.push('FAIL '+e.stack)}finally{await browser.close();fs.writeFileSync('output/playwright/final-results.json',JSON.stringify(results,null,2));console.log(results.join('\n'));if(results.some(x=>x.startsWith('FAIL')))process.exitCode=1}})();
